services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  postgres-create-user:
    image: postgres:15
    container_name: postgres-create-user
    restart: always
    environment:
      POSTGRES_USER: ${CREATE_USER_DB_USER}
      POSTGRES_PASSWORD: ${CREATE_USER_DB_PASSWORD}
      POSTGRES_DB: create_user_db
    volumes:
      - create-user-pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  postgres-notification:
    image: postgres:15
    container_name: postgres-notification
    restart: always
    environment:
      POSTGRES_USER: ${NOTIFICATION_DB_USER}
      POSTGRES_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
      POSTGRES_DB: notification_db
    volumes:
      - notification-pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  create-user-service:
    build:
      context: ./create-user-service
    image: create-user
    container_name: create-user-service
    depends_on:
      - postgres-create-user
      - rabbitmq
    ports:
      - "6000:6000"
    environment:
      PORT: 6000
      DB_HOST: postgres-create-user
      DB_PORT: 5432
      DB_USERNAME: ${CREATE_USER_DB_USER}
      DB_PASSWORD: ${CREATE_USER_DB_PASSWORD}
      DB_DATABASE: create_user_db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672

  notification-service:
    build:
      context: ./notification-service
    image: notification-service
    container_name: notification-service
    depends_on:
      - postgres-notification
      - rabbitmq
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_HOST: postgres-notification
      DB_PORT: 5432
      DB_USERNAME: ${NOTIFICATION_DB_USER}
      DB_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
      DB_DATABASE: notification_db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres-create-user
      - postgres-notification

volumes:
  create-user-pgdata:
  notification-pgdata:
